workflows:
  lidar_scanner_ios:
    name: Lidar Scanner iOS Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - shanin.algerd120209@gmail.com
