name: lidar_scanner_app
description: A 3D scanner using LiDAR for iPhone 13 Pro.
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  file_picker: ^6.1.1

flutter:
  uses-material-design: true
