platform :ios, '10.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  # Формируем корректный путь: берем директорию Podfile и добавляем Flutter/Generated.xcconfig
  generated_xcconfig = File.expand_path(File.join(File.dirname(__FILE__), 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcconfig)
    puts "#{generated_xcconfig} not found, creating empty file."
    # Создаем директорию, если её нет
    dir = File.dirname(generated_xcconfig)
    system("mkdir -p #{dir}")
    File.open(generated_xcconfig, "w") { |f| f.write("") }
  end
  File.foreach(generated_xcconfig) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  return ""
end

def flutter_ios_podfile_setup
  root = flutter_root()  # вызов функции для генерации файла
  require File.expand_path(File.join(File.dirname(__FILE__), 'Flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.dart'))
  flutter_ios_podfile_setup
end

flutter_ios_podfile_setup
