platform :ios, '13.4'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Определяем заглушку для flutter_install_all_ios_pods,
  # чтобы не пытаться загрузить отсутствующий файл podhelper.rb
  def flutter_install_all_ios_pods(root)
    # Пустая реализация – для iOS-сборки через удалённый Mac (Codemagic) стандартная конфигурация Runner уже настроена.
  end
  
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
